sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
script: node_modules/mocha/bin/mocha test/string-class-test.js
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js